import type {
  Deal,
  Task,
  Document,
  SignatureRequest,
  Communication,
  Activity,
  Notification,
  AIInsight,
  AIMessage,
  AnalyticsData,
  KPIData,
  Profile,
} from "@/types";

export const MOCK_TEAM: Profile[] = [
  {
    id: "user-1",
    org_id: "org-1",
    role: "team_coordinator",
    full_name: "Sarah Mitchell",
    email: "sarah@closetrack.co",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    title: "Lead Transaction Coordinator",
    phone: "(555) 234-5678",
    preferences: {},
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "user-2",
    org_id: "org-1",
    role: "agent",
    full_name: "Marcus Johnson",
    email: "marcus@closetrack.co",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus",
    title: "Senior Real Estate Agent",
    phone: "(555) 345-6789",
    preferences: {},
    created_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "user-3",
    org_id: "org-1",
    role: "team_coordinator",
    full_name: "Priya Patel",
    email: "priya@closetrack.co",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
    title: "Transaction Coordinator",
    phone: "(555) 456-7890",
    preferences: {},
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "user-4",
    org_id: "org-1",
    role: "agent",
    full_name: "James Chen",
    email: "james@closetrack.co",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=james",
    title: "Real Estate Agent",
    phone: "(555) 567-8901",
    preferences: {},
    created_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "user-5",
    org_id: "org-1",
    role: "brokerage_admin",
    full_name: "Rachel Torres",
    email: "rachel@closetrack.co",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=rachel",
    title: "Brokerage Manager",
    phone: "(555) 678-9012",
    preferences: {},
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: "deal-1",
    org_id: "org-1",
    address: "1847 Oakwood Drive",
    city: "Austin",
    state: "TX",
    zip: "78701",
    property_type: "single_family",
    status: "active",
    stage: "clear_to_close",
    buyer_name: "David & Emily Park",
    buyer_email: "david.park@email.com",
    buyer_phone: "(555) 111-2222",
    seller_name: "Robert & Linda Chen",
    seller_email: "robert.chen@email.com",
    seller_phone: "(555) 333-4444",
    listing_agent: "Marcus Johnson",
    buyers_agent: "Sarah Mitchell",
    purchase_price: 875000,
    closing_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    contract_date: "2024-11-01",
    earnest_money: 17500,
    down_payment: 175000,
    loan_amount: 700000,
    health_score: 88,
    health_factors: [
      { label: "Days to close", score: 20, max_score: 25, status: "good", description: "5 days remaining" },
      { label: "Pending tasks", score: 22, max_score: 25, status: "good", description: "1 task remaining" },
      { label: "Documents", score: 23, max_score: 25, status: "good", description: "All docs collected" },
      { label: "Communication", score: 23, max_score: 25, status: "good", description: "Active communication" },
    ],
    assigned_to: "user-1",
    created_by: "user-2",
    created_at: "2024-11-01T00:00:00Z",
    updated_at: new Date().toISOString(),
    task_count: 3,
    doc_count: 14,
    pending_sigs: 1,
  },
  {
    id: "deal-2",
    org_id: "org-1",
    address: "4520 Riverside Blvd",
    city: "Denver",
    state: "CO",
    zip: "80202",
    property_type: "condo",
    status: "active",
    stage: "pending_docs",
    buyer_name: "Michael Torres",
    buyer_email: "michael.t@email.com",
    buyer_phone: "(555) 222-3333",
    seller_name: "Susan & Tom Wallace",
    seller_email: "susan.wallace@email.com",
    listing_agent: "James Chen",
    buyers_agent: "Priya Patel",
    purchase_price: 485000,
    closing_date: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    contract_date: "2024-11-08",
    earnest_money: 9700,
    health_score: 62,
    health_factors: [
      { label: "Days to close", score: 18, max_score: 25, status: "warning", description: "18 days remaining" },
      { label: "Pending tasks", score: 14, max_score: 25, status: "warning", description: "4 tasks pending" },
      { label: "Documents", score: 15, max_score: 25, status: "warning", description: "3 docs missing" },
      { label: "Communication", score: 15, max_score: 25, status: "warning", description: "48hr since last contact" },
    ],
    assigned_to: "user-3",
    created_by: "user-4",
    created_at: "2024-11-08T00:00:00Z",
    updated_at: new Date().toISOString(),
    task_count: 7,
    doc_count: 8,
    pending_sigs: 3,
  },
  {
    id: "deal-3",
    org_id: "org-1",
    address: "923 Maple Court",
    city: "Nashville",
    state: "TN",
    zip: "37201",
    property_type: "single_family",
    status: "active",
    stage: "due_diligence",
    buyer_name: "Jennifer & Mark Davis",
    buyer_email: "jennifer.davis@email.com",
    seller_name: "Paul & Grace Kim",
    purchase_price: 620000,
    closing_date: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    contract_date: "2024-11-12",
    earnest_money: 12400,
    health_score: 45,
    health_factors: [
      { label: "Days to close", score: 12, max_score: 25, status: "warning", description: "28 days remaining" },
      { label: "Pending tasks", score: 8, max_score: 25, status: "critical", description: "9 tasks pending" },
      { label: "Documents", score: 10, max_score: 25, status: "critical", description: "5 docs missing" },
      { label: "Communication", score: 15, max_score: 25, status: "warning", description: "Good communication" },
    ],
    assigned_to: "user-1",
    created_by: "user-2",
    created_at: "2024-11-12T00:00:00Z",
    updated_at: new Date().toISOString(),
    task_count: 12,
    doc_count: 5,
    pending_sigs: 4,
  },
  {
    id: "deal-4",
    org_id: "org-1",
    address: "7801 Summit Ridge Rd",
    city: "Phoenix",
    state: "AZ",
    zip: "85001",
    property_type: "townhouse",
    status: "active",
    stage: "under_contract",
    buyer_name: "Carlos Mendez",
    buyer_email: "carlos.m@email.com",
    seller_name: "Amanda Sterling",
    purchase_price: 395000,
    closing_date: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    contract_date: "2024-11-15",
    earnest_money: 7900,
    health_score: 79,
    health_factors: [
      { label: "Days to close", score: 20, max_score: 25, status: "good", description: "35 days remaining" },
      { label: "Pending tasks", score: 20, max_score: 25, status: "good", description: "2 tasks pending" },
      { label: "Documents", score: 18, max_score: 25, status: "good", description: "Most docs received" },
      { label: "Communication", score: 21, max_score: 25, status: "good", description: "Active communication" },
    ],
    assigned_to: "user-3",
    created_by: "user-4",
    created_at: "2024-11-15T00:00:00Z",
    updated_at: new Date().toISOString(),
    task_count: 5,
    doc_count: 7,
    pending_sigs: 2,
  },
  {
    id: "deal-5",
    org_id: "org-1",
    address: "215 Harbor View Lane",
    city: "San Diego",
    state: "CA",
    zip: "92101",
    property_type: "condo",
    status: "active",
    stage: "new_lead",
    buyer_name: "Olivia & Ryan Walsh",
    seller_name: "Thomas Berkley",
    purchase_price: 1200000,
    closing_date: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    contract_date: "2024-11-18",
    earnest_money: 24000,
    health_score: 82,
    health_factors: [
      { label: "Days to close", score: 22, max_score: 25, status: "good", description: "45 days remaining" },
      { label: "Pending tasks", score: 20, max_score: 25, status: "good", description: "3 tasks pending" },
      { label: "Documents", score: 18, max_score: 25, status: "good", description: "Initial docs received" },
      { label: "Communication", score: 22, max_score: 25, status: "good", description: "Great communication" },
    ],
    assigned_to: "user-1",
    created_by: "user-2",
    created_at: "2024-11-18T00:00:00Z",
    updated_at: new Date().toISOString(),
    task_count: 4,
    doc_count: 3,
    pending_sigs: 0,
  },
  {
    id: "deal-6",
    org_id: "org-1",
    address: "3340 Elm Street",
    city: "Charlotte",
    state: "NC",
    zip: "28201",
    property_type: "single_family",
    status: "active",
    stage: "pending_docs",
    buyer_name: "Nathan & Lisa Green",
    seller_name: "Joseph & Marie Blanc",
    purchase_price: 540000,
    closing_date: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    contract_date: "2024-11-05",
    earnest_money: 10800,
    health_score: 55,
    health_factors: [
      { label: "Days to close", score: 15, max_score: 25, status: "warning", description: "22 days remaining" },
      { label: "Pending tasks", score: 12, max_score: 25, status: "warning", description: "6 tasks pending" },
      { label: "Documents", score: 13, max_score: 25, status: "warning", description: "4 docs missing" },
      { label: "Communication", score: 15, max_score: 25, status: "warning", description: "Some delays" },
    ],
    assigned_to: "user-3",
    created_by: "user-2",
    created_at: "2024-11-05T00:00:00Z",
    updated_at: new Date().toISOString(),
    task_count: 8,
    doc_count: 9,
    pending_sigs: 2,
  },
  {
    id: "deal-7",
    org_id: "org-1",
    address: "1156 Willow Creek Dr",
    city: "Seattle",
    state: "WA",
    zip: "98101",
    property_type: "single_family",
    status: "closed",
    stage: "closed",
    buyer_name: "Kevin & Amy Nguyen",
    seller_name: "Patricia Monroe",
    purchase_price: 950000,
    closing_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    contract_date: "2024-10-15",
    earnest_money: 19000,
    health_score: 95,
    health_factors: [
      { label: "Days to close", score: 25, max_score: 25, status: "good", description: "Closed on time" },
      { label: "Pending tasks", score: 25, max_score: 25, status: "good", description: "All tasks complete" },
      { label: "Documents", score: 23, max_score: 25, status: "good", description: "All docs received" },
      { label: "Communication", score: 22, max_score: 25, status: "good", description: "Excellent" },
    ],
    assigned_to: "user-1",
    created_by: "user-2",
    created_at: "2024-10-15T00:00:00Z",
    updated_at: new Date().toISOString(),
    task_count: 18,
    doc_count: 22,
    pending_sigs: 0,
  },
  {
    id: "deal-8",
    org_id: "org-1",
    address: "4892 Lakeside Circle",
    city: "Miami",
    state: "FL",
    zip: "33101",
    property_type: "condo",
    status: "closed",
    stage: "closed",
    buyer_name: "Sofia & Diego Reyes",
    seller_name: "Harold & Joan Fletcher",
    purchase_price: 720000,
    closing_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    contract_date: "2024-10-20",
    earnest_money: 14400,
    health_score: 91,
    health_factors: [
      { label: "Days to close", score: 24, max_score: 25, status: "good", description: "Closed on time" },
      { label: "Pending tasks", score: 25, max_score: 25, status: "good", description: "All tasks complete" },
      { label: "Documents", score: 22, max_score: 25, status: "good", description: "Complete" },
      { label: "Communication", score: 20, max_score: 25, status: "good", description: "Good communication" },
    ],
    assigned_to: "user-3",
    created_by: "user-4",
    created_at: "2024-10-20T00:00:00Z",
    updated_at: new Date().toISOString(),
    task_count: 15,
    doc_count: 18,
    pending_sigs: 0,
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    deal_id: "deal-1",
    deal_address: "1847 Oakwood Drive",
    org_id: "org-1",
    title: "Order final walk-through confirmation",
    description: "Schedule and confirm final walk-through with buyer and seller agent",
    status: "in_progress",
    priority: "critical",
    assigned_to: "user-1",
    assigned_to_name: "Sarah Mitchell",
    due_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    dependencies: [],
    created_by: "user-1",
    created_at: "2024-11-18T00:00:00Z",
    tags: ["closing", "coordination"],
  },
  {
    id: "task-2",
    deal_id: "deal-1",
    deal_address: "1847 Oakwood Drive",
    org_id: "org-1",
    title: "Collect wire transfer instructions",
    status: "pending",
    priority: "critical",
    assigned_to: "user-1",
    assigned_to_name: "Sarah Mitchell",
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    dependencies: [],
    created_by: "user-1",
    created_at: "2024-11-18T00:00:00Z",
    tags: ["closing", "finance"],
  },
  {
    id: "task-3",
    deal_id: "deal-2",
    deal_address: "4520 Riverside Blvd",
    org_id: "org-1",
    title: "Follow up on HOA documents",
    description: "Contact HOA for current meeting minutes and financial statements",
    status: "pending",
    priority: "high",
    assigned_to: "user-3",
    assigned_to_name: "Priya Patel",
    due_date: new Date(Date.now() + 0 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    dependencies: [],
    created_by: "user-3",
    created_at: "2024-11-15T00:00:00Z",
    tags: ["documents", "HOA"],
  },
  {
    id: "task-4",
    deal_id: "deal-2",
    deal_address: "4520 Riverside Blvd",
    org_id: "org-1",
    title: "Request lender commitment letter",
    status: "pending",
    priority: "high",
    assigned_to: "user-3",
    assigned_to_name: "Priya Patel",
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    dependencies: [],
    created_by: "user-3",
    created_at: "2024-11-15T00:00:00Z",
    tags: ["financing", "lender"],
  },
  {
    id: "task-5",
    deal_id: "deal-3",
    deal_address: "923 Maple Court",
    org_id: "org-1",
    title: "Schedule home inspection",
    description: "Book inspection with preferred inspector for next week",
    status: "in_progress",
    priority: "critical",
    assigned_to: "user-1",
    assigned_to_name: "Sarah Mitchell",
    due_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    dependencies: [],
    created_by: "user-2",
    created_at: "2024-11-14T00:00:00Z",
    tags: ["inspection", "due-diligence"],
  },
  {
    id: "task-6",
    deal_id: "deal-3",
    deal_address: "923 Maple Court",
    org_id: "org-1",
    title: "Collect seller disclosure forms",
    status: "blocked",
    priority: "high",
    assigned_to: "user-1",
    assigned_to_name: "Sarah Mitchell",
    due_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    dependencies: [],
    created_by: "user-1",
    created_at: "2024-11-12T00:00:00Z",
    tags: ["disclosure", "documents"],
  },
  {
    id: "task-7",
    deal_id: "deal-4",
    deal_address: "7801 Summit Ridge Rd",
    org_id: "org-1",
    title: "Send purchase contract for review",
    status: "completed",
    priority: "high",
    assigned_to: "user-3",
    assigned_to_name: "Priya Patel",
    due_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    completed_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    dependencies: [],
    created_by: "user-4",
    created_at: "2024-11-10T00:00:00Z",
    tags: ["contract"],
  },
  {
    id: "task-8",
    deal_id: "deal-4",
    deal_address: "7801 Summit Ridge Rd",
    org_id: "org-1",
    title: "Verify title commitment",
    status: "pending",
    priority: "medium",
    assigned_to: "user-3",
    assigned_to_name: "Priya Patel",
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    dependencies: [],
    created_by: "user-3",
    created_at: "2024-11-15T00:00:00Z",
    tags: ["title"],
  },
  {
    id: "task-9",
    deal_id: "deal-5",
    deal_address: "215 Harbor View Lane",
    org_id: "org-1",
    title: "Initial file setup and welcome email",
    status: "completed",
    priority: "medium",
    assigned_to: "user-1",
    assigned_to_name: "Sarah Mitchell",
    due_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    completed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    dependencies: [],
    created_by: "user-1",
    created_at: "2024-11-18T00:00:00Z",
    tags: ["onboarding"],
  },
  {
    id: "task-10",
    deal_id: "deal-6",
    deal_address: "3340 Elm Street",
    org_id: "org-1",
    title: "Request payoff statement from seller",
    status: "pending",
    priority: "high",
    assigned_to: "user-3",
    assigned_to_name: "Priya Patel",
    due_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    dependencies: [],
    created_by: "user-3",
    created_at: "2024-11-10T00:00:00Z",
    tags: ["documents", "financing"],
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "doc-1",
    deal_id: "deal-1",
    deal_address: "1847 Oakwood Drive",
    org_id: "org-1",
    name: "Purchase Agreement - Executed.pdf",
    file_path: "/documents/deal-1/purchase-agreement.pdf",
    file_size: 2457600,
    mime_type: "application/pdf",
    category: "purchase_agreement",
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-01T14:30:00Z",
    version: 3,
    is_signed: true,
  },
  {
    id: "doc-2",
    deal_id: "deal-1",
    deal_address: "1847 Oakwood Drive",
    org_id: "org-1",
    name: "Seller Disclosure Statement.pdf",
    file_path: "/documents/deal-1/disclosure.pdf",
    file_size: 1843200,
    mime_type: "application/pdf",
    category: "disclosure",
    uploaded_by: "user-2",
    uploaded_by_name: "Marcus Johnson",
    created_at: "2024-11-03T10:00:00Z",
    is_signed: true,
  },
  {
    id: "doc-3",
    deal_id: "deal-1",
    deal_address: "1847 Oakwood Drive",
    org_id: "org-1",
    name: "Home Inspection Report.pdf",
    file_path: "/documents/deal-1/inspection.pdf",
    file_size: 5242880,
    mime_type: "application/pdf",
    category: "inspection",
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-08T16:45:00Z",
    ai_extracted: {
      issues_found: 3,
      critical_issues: 0,
      summary: "Property in good condition, minor repairs recommended",
    },
  },
  {
    id: "doc-4",
    deal_id: "deal-2",
    deal_address: "4520 Riverside Blvd",
    org_id: "org-1",
    name: "Purchase Contract.pdf",
    file_path: "/documents/deal-2/contract.pdf",
    file_size: 1966080,
    mime_type: "application/pdf",
    category: "purchase_agreement",
    uploaded_by: "user-3",
    uploaded_by_name: "Priya Patel",
    created_at: "2024-11-08T09:00:00Z",
    is_signed: true,
  },
  {
    id: "doc-5",
    deal_id: "deal-2",
    deal_address: "4520 Riverside Blvd",
    org_id: "org-1",
    name: "HOA Documents - Pending.pdf",
    file_path: "/documents/deal-2/hoa.pdf",
    file_size: 3145728,
    mime_type: "application/pdf",
    category: "disclosure",
    uploaded_by: "user-3",
    uploaded_by_name: "Priya Patel",
    created_at: "2024-11-12T11:30:00Z",
  },
  {
    id: "doc-6",
    deal_id: "deal-3",
    deal_address: "923 Maple Court",
    org_id: "org-1",
    name: "Executed Purchase Agreement.pdf",
    file_path: "/documents/deal-3/agreement.pdf",
    file_size: 2097152,
    mime_type: "application/pdf",
    category: "purchase_agreement",
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-12T14:00:00Z",
    is_signed: true,
  },
  {
    id: "doc-7",
    deal_id: "deal-4",
    deal_address: "7801 Summit Ridge Rd",
    org_id: "org-1",
    name: "Purchase Contract - Draft v2.pdf",
    file_path: "/documents/deal-4/contract-v2.pdf",
    file_size: 1572864,
    mime_type: "application/pdf",
    category: "purchase_agreement",
    uploaded_by: "user-3",
    uploaded_by_name: "Priya Patel",
    created_at: "2024-11-15T16:00:00Z",
    version: 2,
  },
  {
    id: "doc-8",
    deal_id: "deal-5",
    deal_address: "215 Harbor View Lane",
    org_id: "org-1",
    name: "Offer Letter.pdf",
    file_path: "/documents/deal-5/offer.pdf",
    file_size: 1048576,
    mime_type: "application/pdf",
    category: "purchase_agreement",
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-18T10:00:00Z",
  },
];

export const MOCK_SIGNATURE_REQUESTS: SignatureRequest[] = [
  {
    id: "sig-1",
    deal_id: "deal-1",
    deal_address: "1847 Oakwood Drive",
    org_id: "org-1",
    document_id: "doc-1",
    document_name: "Final Closing Disclosure",
    signers: [
      {
        id: "signer-1",
        name: "David Park",
        email: "david.park@email.com",
        role: "Buyer",
        status: "signed",
        signed_at: "2024-11-20T14:30:00Z",
      },
      {
        id: "signer-2",
        name: "Emily Park",
        email: "emily.park@email.com",
        role: "Co-Buyer",
        status: "pending",
      },
    ],
    status: "sent",
    expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    audit_trail: [
      {
        timestamp: "2024-11-20T10:00:00Z",
        event: "Document sent for signature",
        actor: "Sarah Mitchell",
      },
      {
        timestamp: "2024-11-20T14:30:00Z",
        event: "Signed by David Park",
        actor: "David Park",
        ip_address: "192.168.1.1",
      },
    ],
    created_by: "user-1",
    created_at: "2024-11-20T10:00:00Z",
    signing_url: "https://sign.closetrack.co/sig-1",
  },
  {
    id: "sig-2",
    deal_id: "deal-2",
    deal_address: "4520 Riverside Blvd",
    org_id: "org-1",
    document_id: "doc-4",
    document_name: "Purchase Contract",
    signers: [
      {
        id: "signer-3",
        name: "Michael Torres",
        email: "michael.t@email.com",
        role: "Buyer",
        status: "pending",
      },
      {
        id: "signer-4",
        name: "Susan Wallace",
        email: "susan.wallace@email.com",
        role: "Seller",
        status: "pending",
      },
    ],
    status: "pending",
    expires_at: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    audit_trail: [
      {
        timestamp: "2024-11-19T09:00:00Z",
        event: "Signature request created",
        actor: "Priya Patel",
      },
    ],
    created_by: "user-3",
    created_at: "2024-11-19T09:00:00Z",
    signing_url: "https://sign.closetrack.co/sig-2",
  },
];

export const MOCK_COMMUNICATIONS: Communication[] = [
  {
    id: "comm-1",
    deal_id: "deal-1",
    deal_address: "1847 Oakwood Drive",
    org_id: "org-1",
    type: "email",
    subject: "Closing Confirmation - 1847 Oakwood Drive",
    body: "Dear David and Emily, I'm pleased to confirm that we are on track for our scheduled closing...",
    from_email: "sarah@closetrack.co",
    from_name: "Sarah Mitchell",
    to_emails: ["david.park@email.com", "emily.park@email.com"],
    status: "delivered",
    sent_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    thread_id: "thread-1",
  },
  {
    id: "comm-2",
    deal_id: "deal-2",
    deal_address: "4520 Riverside Blvd",
    org_id: "org-1",
    type: "email",
    subject: "Missing Documents Required - 4520 Riverside Blvd",
    body: "Hi Michael, we still need the following documents to proceed: HOA financials, updated lender letter...",
    from_email: "priya@closetrack.co",
    from_name: "Priya Patel",
    to_emails: ["michael.t@email.com"],
    status: "delivered",
    sent_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm-3",
    deal_id: "deal-3",
    deal_address: "923 Maple Court",
    org_id: "org-1",
    type: "note",
    subject: "Inspection Scheduling Note",
    body: "Attempted to reach inspector. Will follow up tomorrow morning. Seller has tight schedule this week.",
    from_email: "sarah@closetrack.co",
    from_name: "Sarah Mitchell",
    to_emails: [],
    status: "sent",
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    org_id: "org-1",
    deal_id: "deal-1",
    deal_address: "1847 Oakwood Drive",
    user_id: "user-1",
    user_name: "Sarah Mitchell",
    type: "signature_completed",
    description: "David Park signed the Closing Disclosure",
    metadata: { document: "Closing Disclosure", signer: "David Park" },
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    icon: "PenLine",
    color: "emerald",
  },
  {
    id: "act-2",
    org_id: "org-1",
    deal_id: "deal-2",
    deal_address: "4520 Riverside Blvd",
    user_id: "user-3",
    user_name: "Priya Patel",
    type: "document_uploaded",
    description: "HOA Documents uploaded to Riverside Blvd deal",
    metadata: { document: "HOA Documents" },
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    icon: "Upload",
    color: "indigo",
  },
  {
    id: "act-3",
    org_id: "org-1",
    deal_id: "deal-4",
    deal_address: "7801 Summit Ridge Rd",
    user_id: "user-3",
    user_name: "Priya Patel",
    type: "task_completed",
    description: "Task 'Send purchase contract for review' marked complete",
    metadata: { task: "Send purchase contract for review" },
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    icon: "CheckCircle",
    color: "emerald",
  },
  {
    id: "act-4",
    org_id: "org-1",
    deal_id: "deal-5",
    deal_address: "215 Harbor View Lane",
    user_id: "user-2",
    user_name: "Marcus Johnson",
    type: "deal_created",
    description: "New deal created for 215 Harbor View Lane, San Diego",
    metadata: { stage: "new_lead", price: 1200000 },
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    icon: "Plus",
    color: "blue",
  },
  {
    id: "act-5",
    org_id: "org-1",
    deal_id: "deal-3",
    deal_address: "923 Maple Court",
    user_id: "user-1",
    user_name: "Sarah Mitchell",
    type: "ai_insight",
    description: "AI flagged risk: Inspection deadline approaching for 923 Maple Court",
    metadata: { risk_type: "deadline", severity: "high" },
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    icon: "Sparkles",
    color: "violet",
  },
  {
    id: "act-6",
    org_id: "org-1",
    deal_id: "deal-7",
    deal_address: "1156 Willow Creek Dr",
    user_id: "user-1",
    user_name: "Sarah Mitchell",
    type: "deal_closed",
    description: "Deal closed successfully — 1156 Willow Creek Dr, Seattle",
    metadata: { sale_price: 950000 },
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    icon: "Trophy",
    color: "amber",
  },
];

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: "insight-1",
    deal_id: "deal-3",
    deal_address: "923 Maple Court",
    type: "risk",
    severity: "critical",
    title: "Inspection deadline in 2 days",
    description: "The inspection contingency window closes in 2 days and no report has been received yet. This could jeopardize the deal.",
    recommended_action: "Contact inspector immediately to confirm scheduling. Consider requesting a 3-day extension.",
    created_at: new Date().toISOString(),
  },
  {
    id: "insight-2",
    deal_id: "deal-2",
    deal_address: "4520 Riverside Blvd",
    type: "risk",
    severity: "high",
    title: "3 documents missing — closing in 18 days",
    description: "HOA financial statements, lender commitment letter, and title insurance binder are still outstanding.",
    recommended_action: "Send automated reminder emails to relevant parties and set up escalation reminders.",
    created_at: new Date().toISOString(),
  },
  {
    id: "insight-3",
    deal_id: "deal-6",
    deal_address: "3340 Elm Street",
    type: "action",
    severity: "high",
    title: "Payoff statement request overdue",
    description: "The payoff statement was due yesterday and has not been received from the seller's lender.",
    recommended_action: "Follow up with seller's agent and escalate to lender directly.",
    created_at: new Date().toISOString(),
  },
  {
    id: "insight-4",
    deal_id: "deal-1",
    deal_address: "1847 Oakwood Drive",
    type: "opportunity",
    severity: "low",
    title: "Deal closing in 5 days — all on track",
    description: "Only 1 signature remaining. Closing is proceeding smoothly.",
    recommended_action: "Send closing confirmation email to all parties.",
    created_at: new Date().toISOString(),
  },
  {
    id: "insight-5",
    type: "reminder",
    severity: "medium",
    title: "4 tasks due today",
    description: "You have 4 tasks across 3 deals due today. 1 is already overdue.",
    recommended_action: "Review and prioritize your task queue.",
    created_at: new Date().toISOString(),
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    user_id: "user-1",
    org_id: "org-1",
    type: "signature_needed",
    title: "Signature needed",
    message: "Emily Park needs to sign the Closing Disclosure for 1847 Oakwood Drive",
    read: false,
    action_url: "/signatures",
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "notif-2",
    user_id: "user-1",
    org_id: "org-1",
    type: "ai_insight",
    title: "AI Risk Alert",
    message: "Inspection deadline approaching for 923 Maple Court — action required",
    read: false,
    action_url: "/deals/deal-3",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif-3",
    user_id: "user-1",
    org_id: "org-1",
    type: "document_uploaded",
    title: "Document uploaded",
    message: "HOA Documents added to 4520 Riverside Blvd deal",
    read: false,
    action_url: "/deals/deal-2",
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "notif-4",
    user_id: "user-1",
    org_id: "org-1",
    type: "task_due",
    title: "Task due today",
    message: "Follow up on HOA documents for 4520 Riverside Blvd",
    read: true,
    action_url: "/tasks",
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_AI_MESSAGES: AIMessage[] = [
  {
    id: "msg-1",
    role: "assistant",
    content: "Hello! I'm your CloseTrack AI assistant. I have full context on your 6 active deals, 28 pending tasks, and team of 5. What would you like to work on today?",
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-2",
    role: "user",
    content: "What deals need my attention most urgently?",
    timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-3",
    role: "assistant",
    content: `Based on your current portfolio, here are the **3 deals requiring immediate attention**:

**🔴 Critical: 923 Maple Court (Nashville, TN)**
- Health Score: 45/100
- Inspection deadline expires in **2 days** — no report received yet
- 5 documents still missing
- Recommended: Contact inspector and consider requesting extension

**🟡 High Priority: 4520 Riverside Blvd (Denver, CO)**
- Health Score: 62/100
- Closing in 18 days with 3 missing docs (HOA financials, lender letter, title binder)
- 4 tasks overdue
- Recommended: Send automated reminders to all parties today

**🟡 Attention Needed: 3340 Elm Street (Charlotte, NC)**
- Health Score: 55/100
- Payoff statement request is overdue
- Recommended: Direct escalation to seller's lender

Your **1847 Oakwood Drive** deal is on track to close in 5 days — great work!

Want me to draft follow-up emails for the critical deals?`,
    timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    tools_used: ["deal_analysis", "risk_scoring"],
  },
];

export const MOCK_ANALYTICS: AnalyticsData = {
  deals_by_month: [
    { month: "Jun", closed: 8, opened: 12, value: 4800000 },
    { month: "Jul", closed: 11, opened: 14, value: 7200000 },
    { month: "Aug", closed: 9, opened: 16, value: 6100000 },
    { month: "Sep", closed: 14, opened: 18, value: 9400000 },
    { month: "Oct", closed: 12, opened: 15, value: 8200000 },
    { month: "Nov", closed: 7, opened: 8, value: 5100000 },
  ],
  pipeline_value_over_time: [
    { date: "2024-06-01", value: 12000000 },
    { date: "2024-07-01", value: 14500000 },
    { date: "2024-08-01", value: 16200000 },
    { date: "2024-09-01", value: 19800000 },
    { date: "2024-10-01", value: 22100000 },
    { date: "2024-11-01", value: 24600000 },
  ],
  task_completion_rate: [
    { week: "Oct W1", rate: 78, completed: 42, total: 54 },
    { week: "Oct W2", rate: 85, completed: 51, total: 60 },
    { week: "Oct W3", rate: 82, completed: 45, total: 55 },
    { week: "Oct W4", rate: 91, completed: 61, total: 67 },
    { week: "Nov W1", rate: 88, completed: 52, total: 59 },
    { week: "Nov W2", rate: 79, completed: 38, total: 48 },
  ],
  stage_distribution: [
    { stage: "New Lead", count: 1, value: 1200000 },
    { stage: "Under Contract", count: 1, value: 395000 },
    { stage: "Due Diligence", count: 1, value: 620000 },
    { stage: "Pending Docs", count: 2, value: 1025000 },
    { stage: "Clear to Close", count: 1, value: 875000 },
    { stage: "Closed", count: 2, value: 1670000 },
  ],
  team_performance: [
    { name: "Sarah Mitchell", deals_closed: 8, avg_days: 28, revenue: 5200000 },
    { name: "Priya Patel", deals_closed: 6, avg_days: 31, revenue: 3800000 },
    { name: "Marcus Johnson", deals_closed: 5, avg_days: 34, revenue: 4100000 },
    { name: "James Chen", deals_closed: 4, avg_days: 29, revenue: 2700000 },
  ],
  health_distribution: [
    { deal: "Oakwood Dr", health_score: 88, days_to_close: 5 },
    { deal: "Riverside Blvd", health_score: 62, days_to_close: 18 },
    { deal: "Maple Court", health_score: 45, days_to_close: 28 },
    { deal: "Summit Ridge", health_score: 79, days_to_close: 35 },
    { deal: "Harbor View", health_score: 82, days_to_close: 45 },
    { deal: "Elm Street", health_score: 55, days_to_close: 22 },
  ],
};

export const MOCK_KPI: KPIData = {
  active_deals: 6,
  active_deals_trend: 12,
  tasks_due_today: 4,
  tasks_overdue: 2,
  docs_pending_signature: 5,
  closings_this_month: 7,
  closings_revenue: 5100000,
  closings_trend: -8,
};
