import type { ClientPortalData } from "@/types/portal";

export const MOCK_CLIENT_PORTAL: ClientPortalData = {
  token: "demo-token-2024",
  clientName: "Marcus & Elena Reyes",
  clientEmail: "marcus.reyes@email.com",
  clientInitials: "MR",
  dealId: "deal-001",
  propertyAddress: "2847 Meridian Oak Drive",
  propertyCity: "Austin, TX 78701",
  propertyType: "Single Family Home",
  purchasePrice: 685000,
  closingDate: "2025-07-15",
  contractDate: "2025-06-01",
  currentStage: "due_diligence",
  healthScore: 82,
  unreadMessages: 2,
  pendingTasks: 3,
  docsComplete: 8,
  docsTotal: 12,
  welcomeMessage:
    "Your transaction is on track. Our team is here every step of the way — reach out anytime.",

  milestones: [
    {
      id: "m1",
      label: "Offer Accepted",
      description: "Your offer was accepted by the seller.",
      date: "2025-06-01",
      status: "completed",
      icon: "CheckCircle",
      subSteps: [
        { label: "Offer submitted", completed: true },
        { label: "Counter offer reviewed", completed: true },
        { label: "Offer accepted by seller", completed: true },
      ],
      aiExplainer:
        "Your offer was accepted — this means you and the seller have agreed on price and terms. The transaction is now officially underway.",
    },
    {
      id: "m2",
      label: "Earnest Money Deposited",
      description: "Earnest money deposit confirmed.",
      date: "2025-06-04",
      status: "completed",
      icon: "DollarSign",
      subSteps: [
        { label: "EMD wired to escrow", completed: true },
        { label: "Escrow confirmed receipt", completed: true },
      ],
      aiExplainer:
        "Earnest money is a deposit showing you're serious about the purchase. It will be applied toward your down payment at closing.",
    },
    {
      id: "m3",
      label: "Home Inspection",
      description: "Professional inspection of the property completed.",
      date: "2025-06-10",
      status: "completed",
      icon: "Search",
      subSteps: [
        { label: "Inspector scheduled", completed: true },
        { label: "Inspection completed", completed: true },
        { label: "Report delivered", completed: true },
      ],
      aiExplainer:
        "A licensed home inspector assessed the property's condition. The report identifies any issues so you can negotiate repairs or credits before closing.",
    },
    {
      id: "m4",
      label: "Appraisal",
      description: "Lender-ordered property appraisal in progress.",
      date: "2025-06-18",
      status: "active",
      icon: "BarChart3",
      subSteps: [
        { label: "Appraisal ordered by lender", completed: true },
        { label: "Appraiser visit scheduled", completed: true },
        { label: "Appraisal report received", completed: false },
      ],
      aiExplainer:
        "Your lender hired an independent appraiser to confirm the home's market value. This ensures the loan amount is appropriate for the property.",
    },
    {
      id: "m5",
      label: "Financing Approved",
      description: "Final loan approval from your lender.",
      date: "2025-06-28",
      status: "upcoming",
      icon: "Shield",
      subSteps: [
        { label: "Loan application submitted", completed: false },
        { label: "Underwriting review", completed: false },
        { label: "Clear to close issued", completed: false },
      ],
      aiExplainer:
        "After underwriting, your lender will issue a 'Clear to Close' — this is the final approval for your mortgage. No major financial changes before this step.",
    },
    {
      id: "m6",
      label: "Documents & Disclosures",
      description: "All required documents signed and delivered.",
      date: "2025-07-05",
      status: "upcoming",
      icon: "FileText",
      subSteps: [
        { label: "Title search complete", completed: false },
        { label: "Disclosure documents signed", completed: false },
        { label: "Final walkthrough scheduled", completed: false },
      ],
      aiExplainer:
        "This phase covers all legal documents — title confirms there are no claims on the property, disclosures inform you of known issues, and the walkthrough confirms condition.",
    },
    {
      id: "m7",
      label: "Final Walkthrough",
      description: "Last chance to inspect the property before closing.",
      date: "2025-07-13",
      status: "upcoming",
      icon: "Home",
      subSteps: [
        { label: "Walkthrough scheduled", completed: false },
        { label: "Walkthrough completed", completed: false },
      ],
      aiExplainer:
        "The final walkthrough is your last opportunity to verify the property is in the agreed-upon condition and all negotiated repairs have been completed.",
    },
    {
      id: "m8",
      label: "Closing Day",
      description: "Sign final documents and receive your keys.",
      date: "2025-07-15",
      status: "upcoming",
      icon: "Key",
      subSteps: [
        { label: "Closing disclosure reviewed", completed: false },
        { label: "Wire transfer confirmed", completed: false },
        { label: "Documents signed", completed: false },
        { label: "Keys received", completed: false },
      ],
      aiExplainer:
        "On closing day you'll sign final documents, funds will be transferred, and you'll receive the keys to your new home. Congratulations in advance!",
    },
  ],

  tasks: [
    {
      id: "ct1",
      type: "upload",
      title: "Upload Proof of Homeowner's Insurance",
      description:
        "Your lender requires proof of insurance before closing. Upload your binder or declarations page.",
      dueDate: "2025-06-20",
      status: "pending",
      priority: "urgent",
    },
    {
      id: "ct2",
      type: "sign",
      title: "Sign Seller Disclosure Form",
      description:
        "Review and sign the seller's property disclosure statement. This is required before the appraisal is finalized.",
      dueDate: "2025-06-19",
      status: "overdue",
      priority: "urgent",
      documentId: "doc-003",
      documentName: "Seller Disclosure Statement",
    },
    {
      id: "ct3",
      type: "review",
      title: "Review Home Inspection Report",
      description:
        "Your inspection report is ready. Review the findings and let your agent know if you'd like to request repairs.",
      dueDate: "2025-06-22",
      status: "pending",
      priority: "normal",
      documentId: "doc-004",
      documentName: "Home Inspection Report",
    },
    {
      id: "ct4",
      type: "action",
      title: "Confirm Wire Transfer Instructions",
      description:
        "Verify closing wire instructions directly with your escrow officer. Never send wire based on email instructions alone.",
      dueDate: "2025-07-10",
      status: "pending",
      priority: "normal",
    },
    {
      id: "ct5",
      type: "schedule",
      title: "Schedule Final Walkthrough",
      description:
        "Coordinate with your agent to schedule the final walkthrough 1-2 days before closing.",
      dueDate: "2025-07-12",
      status: "pending",
      priority: "low",
    },
  ],

  documents: [
    {
      id: "doc-001",
      name: "Purchase & Sale Agreement",
      category: "contract",
      status: "signed",
      date: "2025-06-01",
      size: "2.4 MB",
      aiSummary:
        "3-page agreement covering purchase price of $685,000, closing date of July 15, and standard contingencies including inspection and financing.",
      requiresSignature: false,
    },
    {
      id: "doc-002",
      name: "Earnest Money Receipt",
      category: "contract",
      status: "uploaded",
      date: "2025-06-04",
      size: "0.3 MB",
    },
    {
      id: "doc-003",
      name: "Seller Disclosure Statement",
      category: "disclosure",
      status: "action_required",
      date: "2025-06-08",
      size: "1.8 MB",
      aiSummary:
        "Seller discloses prior roof repair (2021), updated HVAC (2022), and no known foundation issues. Review Section 4 regarding drainage easement.",
      requiresSignature: true,
    },
    {
      id: "doc-004",
      name: "Home Inspection Report",
      category: "inspection",
      status: "pending",
      date: "2025-06-10",
      size: "8.7 MB",
      aiSummary:
        "47-page report. 3 major items flagged: attic insulation below code, minor GFCI outlet issues in bathrooms, and recommend servicing water heater. 12 minor items.",
    },
    {
      id: "doc-005",
      name: "HOA Disclosure Package",
      category: "disclosure",
      status: "uploaded",
      date: "2025-06-12",
      size: "4.2 MB",
      aiSummary:
        "HOA fees: $185/month. Covers landscaping and common areas. Current reserve fund is adequately funded. No pending special assessments.",
    },
    {
      id: "doc-006",
      name: "Loan Estimate",
      category: "financing",
      status: "reviewed",
      date: "2025-06-05",
      size: "0.9 MB",
      aiSummary:
        "30-year fixed at 6.875%. Estimated monthly payment: $3,842. Closing costs estimated at $14,200. Rate lock expires July 1.",
    },
    {
      id: "doc-007",
      name: "Title Commitment",
      category: "contract",
      status: "pending",
      date: "2025-06-14",
      size: "1.2 MB",
    },
    {
      id: "doc-008",
      name: "Appraisal Report",
      category: "financing",
      status: "pending",
      date: "2025-06-18",
      size: "—",
    },
    {
      id: "doc-009",
      name: "Proof of Homeowner's Insurance",
      category: "closing",
      status: "action_required",
      date: "—",
      size: "—",
      requiresSignature: false,
    },
    {
      id: "doc-010",
      name: "Final Closing Disclosure",
      category: "closing",
      status: "pending",
      date: "—",
      size: "—",
    },
    {
      id: "doc-011",
      name: "Wire Transfer Instructions",
      category: "closing",
      status: "pending",
      date: "—",
      size: "—",
    },
    {
      id: "doc-012",
      name: "Property Survey",
      category: "other",
      status: "uploaded",
      date: "2025-06-09",
      size: "3.1 MB",
      aiSummary:
        "Survey confirms lot size of 0.28 acres. No encroachments found. Easements along rear 10 feet of property for utility access.",
    },
  ],

  contacts: [
    {
      id: "c1",
      name: "Sarah Mitchell",
      role: "Transaction Coordinator",
      email: "sarah@closetrack.co",
      phone: "(512) 555-0182",
      avatarInitials: "SM",
      avatarColor: "indigo",
      available: true,
    },
    {
      id: "c2",
      name: "James Thornton",
      role: "Buyer's Agent",
      email: "james@realtypros.com",
      phone: "(512) 555-0247",
      avatarInitials: "JT",
      avatarColor: "teal",
      available: true,
    },
    {
      id: "c3",
      name: "Linda Park",
      role: "Escrow Officer",
      email: "lpark@firstescrow.com",
      phone: "(512) 555-0391",
      avatarInitials: "LP",
      avatarColor: "violet",
      available: false,
    },
    {
      id: "c4",
      name: "Derek Vasquez",
      role: "Loan Officer",
      email: "dvasquez@westernfunding.com",
      phone: "(512) 555-0158",
      avatarInitials: "DV",
      avatarColor: "emerald",
      available: true,
    },
    {
      id: "c5",
      name: "Olivia Chen",
      role: "Title Officer",
      email: "ochen@premiumtitle.com",
      phone: "(512) 555-0274",
      avatarInitials: "OC",
      avatarColor: "amber",
      available: true,
    },
    {
      id: "c6",
      name: "Marcus Reyes",
      role: "Home Inspector",
      email: "m.reyes@austininspect.com",
      phone: "(512) 555-0463",
      avatarInitials: "MR",
      avatarColor: "rose",
      available: false,
    },
  ],

  messages: [
    {
      id: "msg-1",
      sender: "team",
      senderName: "Sarah Mitchell",
      senderInitials: "SM",
      content:
        "Hi Marcus & Elena! Welcome to your CloseTrack portal. This is where we'll coordinate everything for your purchase of 2847 Meridian Oak Drive. Feel free to message us any time with questions.",
      timestamp: "2025-06-01T09:15:00Z",
      read: true,
    },
    {
      id: "msg-2",
      sender: "client",
      senderName: "Marcus Reyes",
      senderInitials: "MR",
      content:
        "Thank you! We're very excited. Quick question — when should we expect the inspection report?",
      timestamp: "2025-06-01T11:32:00Z",
      read: true,
    },
    {
      id: "msg-3",
      sender: "team",
      senderName: "Sarah Mitchell",
      senderInitials: "SM",
      content:
        "The inspection is scheduled for June 10th. You'll receive the full report within 24 hours after the inspector completes their visit. The inspector is Dave Hollis — very thorough, great reputation.",
      timestamp: "2025-06-01T11:45:00Z",
      read: true,
    },
    {
      id: "msg-4",
      sender: "team",
      senderName: "James Thornton",
      senderInitials: "JT",
      content:
        "Just a heads up — the appraisal appointment is scheduled for June 18th between 10am-12pm. The appraiser will need access to the property, so the listing agent is coordinating.",
      timestamp: "2025-06-11T14:20:00Z",
      read: true,
    },
    {
      id: "msg-5",
      sender: "client",
      senderName: "Elena Reyes",
      senderInitials: "ER",
      content:
        "Perfect, thank you James. We reviewed the inspection report — we'd like to request that the attic insulation and GFCI outlets be addressed. Can we submit a repair request?",
      timestamp: "2025-06-12T16:05:00Z",
      read: true,
    },
    {
      id: "msg-6",
      sender: "team",
      senderName: "Sarah Mitchell",
      senderInitials: "SM",
      content:
        "Absolutely. I've drafted the repair addendum based on your notes. Please review the document in your portal — it will be ready for your signature once James finalizes the language with the seller's agent.",
      timestamp: "2025-06-13T09:00:00Z",
      read: true,
    },
    {
      id: "msg-7",
      sender: "team",
      senderName: "Sarah Mitchell",
      senderInitials: "SM",
      content:
        "Reminder: your Seller Disclosure form is ready to sign in the Documents tab. Please complete this by June 19th. Let me know if you have any questions about specific items in the disclosure.",
      timestamp: "2025-06-15T10:30:00Z",
      read: false,
    },
    {
      id: "msg-8",
      sender: "team",
      senderName: "Derek Vasquez",
      senderInitials: "DV",
      content:
        "Quick update from the lending side — your file is in underwriting. Please upload your proof of homeowner's insurance when you have it ready. This is needed before we can issue the Clear to Close.",
      timestamp: "2025-06-16T15:45:00Z",
      read: false,
    },
  ],

  activities: [
    {
      id: "act-1",
      title: "Inspection Report Delivered",
      description: "Home inspection report uploaded by Dave Hollis.",
      timestamp: "2025-06-10T17:00:00Z",
      type: "document",
      icon: "FileText",
    },
    {
      id: "act-2",
      title: "HOA Documents Received",
      description: "HOA disclosure package added to your documents.",
      timestamp: "2025-06-12T11:00:00Z",
      type: "document",
      icon: "FolderOpen",
    },
    {
      id: "act-3",
      title: "Milestone: Home Inspection Completed",
      description: "Home inspection milestone marked complete.",
      timestamp: "2025-06-10T18:00:00Z",
      type: "milestone",
      icon: "CheckCircle",
    },
    {
      id: "act-4",
      title: "Appraisal Ordered",
      description: "Lender ordered appraisal. Appointment scheduled June 18.",
      timestamp: "2025-06-11T09:00:00Z",
      type: "milestone",
      icon: "BarChart3",
    },
    {
      id: "act-5",
      title: "New Message from Sarah Mitchell",
      description: "Your coordinator sent a reminder about the disclosure form.",
      timestamp: "2025-06-15T10:30:00Z",
      type: "message",
      icon: "MessageSquare",
    },
    {
      id: "act-6",
      title: "Task Added: Upload Insurance",
      description: "New task: Upload proof of homeowner's insurance.",
      timestamp: "2025-06-16T15:45:00Z",
      type: "task",
      icon: "CheckSquare",
    },
  ],
};
