import type { MediaItem } from "@/types/media";

function p(seed: string, w: number, h: number) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

export const MOCK_MEDIA: MediaItem[] = [
  // ─── Deal 1: 1847 Oakwood Drive ────────────────────────────────────────────
  {
    id: "m-1",
    deal_id: "deal-1",
    name: "Front Exterior",
    url: p("oakwood-ext1", 900, 600),
    thumbnail_url: p("oakwood-ext1", 400, 267),
    category: "exterior",
    type: "photo",
    source: "local",
    is_cover: true,
    is_featured: true,
    width: 900,
    height: 600,
    file_size: 2_400_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-02T10:00:00Z",
    ai_analysis: {
      room_type: "Exterior",
      detected_features: ["Front yard", "2-car garage", "Landscaping", "Driveway"],
      quality_score: 94,
      issues: [],
      tags: ["curb-appeal", "landscaped", "well-maintained", "move-in-ready"],
      description: "Charming single-family home with excellent curb appeal. Mature landscaping, clean driveway, and an attached 2-car garage.",
      marketing_caption: "Welcome home! This beautifully landscaped property offers undeniable curb appeal and a warm, inviting entrance.",
    },
  },
  {
    id: "m-2",
    deal_id: "deal-1",
    name: "Side Yard View",
    url: p("oakwood-ext2", 900, 700),
    thumbnail_url: p("oakwood-ext2", 400, 311),
    category: "exterior",
    type: "photo",
    source: "google_drive",
    drive_file_id: "drive-file-101",
    drive_sync_status: "synced",
    is_cover: false,
    is_featured: false,
    width: 900,
    height: 700,
    file_size: 2_100_000,
    uploaded_by: "user-2",
    uploaded_by_name: "Marcus Johnson",
    created_at: "2024-11-02T10:30:00Z",
    ai_analysis: {
      room_type: "Exterior",
      detected_features: ["Side yard", "Fence", "Gate", "Trees"],
      quality_score: 82,
      issues: [],
      tags: ["side-yard", "privacy-fence", "mature-trees"],
      description: "Private side yard with privacy fencing and mature trees providing excellent shade.",
      marketing_caption: "Enjoy the fully fenced side yard — perfect for privacy and outdoor living.",
    },
  },
  {
    id: "m-3",
    deal_id: "deal-1",
    name: "Kitchen — Main",
    url: p("oakwood-kitchen1", 900, 600),
    thumbnail_url: p("oakwood-kitchen1", 400, 267),
    category: "kitchen",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: true,
    width: 900,
    height: 600,
    file_size: 2_200_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-02T11:00:00Z",
    ai_analysis: {
      room_type: "Kitchen",
      detected_features: ["Island", "Granite countertops", "Stainless appliances", "Recessed lighting"],
      quality_score: 91,
      issues: [],
      tags: ["gourmet-kitchen", "granite", "stainless-steel", "island", "updated"],
      description: "Fully updated chef's kitchen featuring granite countertops, a large center island, and premium stainless steel appliances.",
      marketing_caption: "Cook in style! This stunning gourmet kitchen features granite counters, a spacious island, and top-of-the-line stainless appliances.",
    },
  },
  {
    id: "m-4",
    deal_id: "deal-1",
    name: "Kitchen — Dining Area",
    url: p("oakwood-kitchen2", 900, 650),
    thumbnail_url: p("oakwood-kitchen2", 400, 289),
    category: "kitchen",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: false,
    width: 900,
    height: 650,
    file_size: 1_900_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-02T11:15:00Z",
    ai_analysis: {
      room_type: "Kitchen/Dining",
      detected_features: ["Breakfast nook", "Large windows", "Natural light"],
      quality_score: 88,
      issues: [],
      tags: ["breakfast-nook", "natural-light", "open-concept"],
      description: "Open-concept kitchen flows seamlessly into a bright breakfast nook with large windows overlooking the backyard.",
      marketing_caption: "Morning coffee never looked this good — the bright breakfast nook fills with natural light every morning.",
    },
  },
  {
    id: "m-5",
    deal_id: "deal-1",
    name: "Living Room",
    url: p("oakwood-living1", 900, 600),
    thumbnail_url: p("oakwood-living1", 400, 267),
    category: "living_room",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: true,
    width: 900,
    height: 600,
    file_size: 2_350_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-02T11:30:00Z",
    ai_analysis: {
      room_type: "Living Room",
      detected_features: ["Fireplace", "Hardwood floors", "Crown molding", "Bay window"],
      quality_score: 96,
      issues: [],
      tags: ["fireplace", "hardwood", "crown-molding", "spacious", "bright"],
      description: "Elegant living room showcasing original hardwood floors, a wood-burning fireplace, and beautiful crown molding throughout.",
      marketing_caption: "Gather around the fireplace in this stunning living room — the perfect blend of elegance and comfort.",
    },
  },
  {
    id: "m-6",
    deal_id: "deal-1",
    name: "Master Bedroom",
    url: p("oakwood-bed1", 900, 650),
    thumbnail_url: p("oakwood-bed1", 400, 289),
    category: "bedroom",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: true,
    width: 900,
    height: 650,
    file_size: 2_150_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-02T12:00:00Z",
    ai_analysis: {
      room_type: "Master Bedroom",
      detected_features: ["Walk-in closet", "En-suite bath", "Tray ceiling", "Ceiling fan"],
      quality_score: 90,
      issues: [],
      tags: ["master-suite", "walk-in-closet", "tray-ceiling", "spacious"],
      description: "Spacious master suite featuring a tray ceiling, walk-in closet, and direct access to the en-suite master bath.",
      marketing_caption: "Your private retreat awaits — the master suite offers a tray ceiling, generous closet space, and a spa-like en-suite.",
    },
  },
  {
    id: "m-7",
    deal_id: "deal-1",
    name: "Guest Bedroom",
    url: p("oakwood-bed2", 900, 600),
    thumbnail_url: p("oakwood-bed2", 400, 267),
    category: "bedroom",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: false,
    width: 900,
    height: 600,
    file_size: 1_850_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-02T12:15:00Z",
    ai_analysis: {
      room_type: "Bedroom",
      detected_features: ["Closet", "Natural light", "Neutral paint"],
      quality_score: 85,
      issues: [],
      tags: ["guest-room", "neutral-colors", "natural-light"],
      description: "Comfortable secondary bedroom with generous closet space and great natural light.",
      marketing_caption: "Guests will feel right at home in this bright and welcoming secondary bedroom.",
    },
  },
  {
    id: "m-8",
    deal_id: "deal-1",
    name: "Master Bathroom",
    url: p("oakwood-bath1", 900, 700),
    thumbnail_url: p("oakwood-bath1", 400, 311),
    category: "bathroom",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: true,
    width: 900,
    height: 700,
    file_size: 2_000_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-02T12:30:00Z",
    ai_analysis: {
      room_type: "Master Bathroom",
      detected_features: ["Double vanity", "Soaking tub", "Walk-in shower", "Heated floors"],
      quality_score: 93,
      issues: [],
      tags: ["spa-bath", "double-vanity", "soaking-tub", "walk-in-shower", "luxury"],
      description: "Luxurious master bathroom featuring a double vanity, freestanding soaking tub, oversized walk-in shower, and heated tile floors.",
      marketing_caption: "Experience spa-like luxury every day — the master bath is a true sanctuary with soaking tub and walk-in shower.",
    },
  },
  {
    id: "m-9",
    deal_id: "deal-1",
    name: "Backyard & Deck",
    url: p("oakwood-yard1", 900, 600),
    thumbnail_url: p("oakwood-yard1", 400, 267),
    category: "backyard",
    type: "photo",
    source: "google_drive",
    drive_file_id: "drive-file-102",
    drive_sync_status: "synced",
    is_cover: false,
    is_featured: true,
    width: 900,
    height: 600,
    file_size: 2_600_000,
    uploaded_by: "user-2",
    uploaded_by_name: "Marcus Johnson",
    created_at: "2024-11-03T09:00:00Z",
    ai_analysis: {
      room_type: "Backyard",
      detected_features: ["Deck", "Privacy fence", "Garden area", "Outdoor dining space"],
      quality_score: 89,
      issues: [],
      tags: ["outdoor-living", "deck", "privacy-fence", "entertainer"],
      description: "Impressive backyard oasis with a large entertainer's deck, privacy fencing, and professionally landscaped garden areas.",
      marketing_caption: "Summer is calling! This stunning backyard deck was made for outdoor entertaining.",
    },
  },
  {
    id: "m-10",
    deal_id: "deal-1",
    name: "Garage Interior",
    url: p("oakwood-garage1", 900, 600),
    thumbnail_url: p("oakwood-garage1", 400, 267),
    category: "garage",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: false,
    width: 900,
    height: 600,
    file_size: 1_700_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-03T09:30:00Z",
    ai_analysis: {
      room_type: "Garage",
      detected_features: ["Epoxy floor", "Storage shelving", "Workbench", "Insulated door"],
      quality_score: 80,
      issues: [],
      tags: ["2-car-garage", "epoxy-floor", "storage", "organized"],
      description: "Clean and organized 2-car garage with epoxy flooring, built-in storage shelving, and workbench area.",
      marketing_caption: "Car enthusiasts and DIYers will love the finished 2-car garage with epoxy floors and built-in storage.",
    },
  },
  {
    id: "m-11",
    deal_id: "deal-1",
    name: "Final Walk-Through",
    url: p("oakwood-closing1", 900, 600),
    thumbnail_url: p("oakwood-closing1", 400, 267),
    category: "closing",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: false,
    width: 900,
    height: 600,
    file_size: 2_000_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-05T14:00:00Z",
    notes: "Final walk-through completed. All items in good condition.",
    ai_analysis: {
      room_type: "Living Room",
      detected_features: ["Empty", "Clean", "Move-in ready"],
      quality_score: 75,
      issues: [],
      tags: ["walk-through", "closing", "vacant", "move-in-ready"],
      description: "Property cleared and ready for closing. Clean and in excellent condition for the new owners.",
      marketing_caption: "Ready for its new chapter — this home is move-in ready and waiting for you.",
    },
  },

  // ─── Deal 2: 4520 Riverside Blvd ────────────────────────────────────────────
  {
    id: "m-12",
    deal_id: "deal-2",
    name: "Exterior — Front",
    url: p("riverside-ext1", 900, 600),
    thumbnail_url: p("riverside-ext1", 400, 267),
    category: "exterior",
    type: "photo",
    source: "local",
    is_cover: true,
    is_featured: true,
    width: 900,
    height: 600,
    file_size: 2_100_000,
    uploaded_by: "user-3",
    uploaded_by_name: "Priya Patel",
    created_at: "2024-11-10T09:00:00Z",
    ai_analysis: {
      room_type: "Exterior",
      detected_features: ["Condo building", "Parking", "Riverfront view"],
      quality_score: 86,
      issues: [],
      tags: ["condo", "riverfront", "modern-building"],
      description: "Modern condo building with riverfront views and covered parking.",
      marketing_caption: "Wake up to river views every morning in this stunning condo.",
    },
  },
  {
    id: "m-13",
    deal_id: "deal-2",
    name: "Living Area",
    url: p("riverside-living1", 900, 600),
    thumbnail_url: p("riverside-living1", 400, 267),
    category: "living_room",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: false,
    width: 900,
    height: 600,
    file_size: 1_800_000,
    uploaded_by: "user-3",
    uploaded_by_name: "Priya Patel",
    created_at: "2024-11-10T09:30:00Z",
    ai_analysis: {
      room_type: "Living Room",
      detected_features: ["Open floor plan", "Large windows", "City views"],
      quality_score: 88,
      issues: [],
      tags: ["open-concept", "city-views", "bright"],
      description: "Bright open-concept living area with floor-to-ceiling windows offering stunning river and city views.",
      marketing_caption: "Entertain with a view — the open living area frames breathtaking river panoramas.",
    },
  },
  {
    id: "m-14",
    deal_id: "deal-2",
    name: "Kitchen",
    url: p("riverside-kitchen1", 900, 650),
    thumbnail_url: p("riverside-kitchen1", 400, 289),
    category: "kitchen",
    type: "photo",
    source: "google_drive",
    drive_file_id: "drive-file-201",
    drive_sync_status: "synced",
    is_cover: false,
    is_featured: false,
    width: 900,
    height: 650,
    file_size: 2_000_000,
    uploaded_by: "user-3",
    uploaded_by_name: "Priya Patel",
    created_at: "2024-11-10T10:00:00Z",
    ai_analysis: {
      room_type: "Kitchen",
      detected_features: ["Quartz countertops", "Subway tile backsplash", "Gas range"],
      quality_score: 87,
      issues: [],
      tags: ["quartz", "gas-range", "modern-kitchen"],
      description: "Sleek modern kitchen with quartz countertops, subway tile backsplash, and high-end gas range.",
      marketing_caption: "Cook like a pro in this magazine-worthy kitchen with quartz counters and professional gas range.",
    },
  },
  {
    id: "m-15",
    deal_id: "deal-2",
    name: "Master Bedroom — Missing",
    url: p("riverside-bed1", 900, 600),
    thumbnail_url: p("riverside-bed1", 400, 267),
    category: "bedroom",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: false,
    width: 900,
    height: 600,
    file_size: 1_950_000,
    uploaded_by: "user-3",
    uploaded_by_name: "Priya Patel",
    created_at: "2024-11-10T10:30:00Z",
    ai_analysis: {
      room_type: "Bedroom",
      detected_features: ["Closet", "Window", "Carpeted"],
      quality_score: 72,
      issues: ["Low lighting", "Image slightly blurred"],
      tags: ["bedroom", "natural-light"],
      description: "Standard bedroom with closet and natural light. Better photography recommended.",
      marketing_caption: "Comfortable and cozy bedroom with great natural light.",
    },
  },

  // ─── Deal 3: 923 Maple Court ─────────────────────────────────────────────────
  {
    id: "m-16",
    deal_id: "deal-3",
    name: "Exterior",
    url: p("maple-ext1", 900, 600),
    thumbnail_url: p("maple-ext1", 400, 267),
    category: "exterior",
    type: "photo",
    source: "local",
    is_cover: true,
    is_featured: false,
    width: 900,
    height: 600,
    file_size: 2_300_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-14T09:00:00Z",
    ai_analysis: {
      room_type: "Exterior",
      detected_features: ["Front yard", "Single-story", "Driveway"],
      quality_score: 68,
      issues: ["Overgrown lawn", "Faded paint on trim"],
      tags: ["needs-attention", "fixer-upper"],
      description: "Single-story property with deferred maintenance visible on exterior. Overgrown lawn and faded trim noted.",
      marketing_caption: "Priced to sell — this home has excellent bones and is ready for your personal touch.",
    },
  },
  {
    id: "m-17",
    deal_id: "deal-3",
    name: "Inspection — Roof Issue",
    url: p("maple-insp1", 900, 600),
    thumbnail_url: p("maple-insp1", 400, 267),
    category: "inspection",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: false,
    width: 900,
    height: 600,
    file_size: 1_600_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-14T11:00:00Z",
    notes: "Inspector flagged roof repair needed — 3 damaged shingles near ridge.",
    ai_analysis: {
      room_type: "Roof/Exterior",
      detected_features: ["Roof", "Shingles", "Chimney"],
      quality_score: 45,
      issues: ["Damaged shingles", "Potential leak risk", "Needs professional repair"],
      tags: ["inspection", "roof-repair", "flagged", "urgent"],
      description: "Inspection photo showing damaged shingles near roof ridge. Professional repair estimated at $2,400-$3,800.",
      marketing_caption: "Post-repair, this home's roof will be in excellent condition.",
    },
  },
  {
    id: "m-18",
    deal_id: "deal-3",
    name: "Inspection — HVAC",
    url: p("maple-insp2", 900, 600),
    thumbnail_url: p("maple-insp2", 400, 267),
    category: "inspection",
    type: "photo",
    source: "local",
    is_cover: false,
    is_featured: false,
    width: 900,
    height: 600,
    file_size: 1_500_000,
    uploaded_by: "user-1",
    uploaded_by_name: "Sarah Mitchell",
    created_at: "2024-11-14T11:30:00Z",
    notes: "HVAC unit is 14 years old. Inspector recommends budgeting for replacement within 2-3 years.",
    ai_analysis: {
      room_type: "Utility/Mechanical",
      detected_features: ["HVAC unit", "Ductwork", "Age indicators"],
      quality_score: 52,
      issues: ["Unit age 14 years", "Recommend budget for replacement", "Minor rust on housing"],
      tags: ["inspection", "hvac", "aging-system", "budget-item"],
      description: "HVAC unit showing normal wear for age. Functional but approaching end of typical service life.",
      marketing_caption: "Updated systems throughout — this home has been well-maintained.",
    },
  },
];

export function getMediaByDeal(dealId: string): MediaItem[] {
  return MOCK_MEDIA.filter((m) => m.deal_id === dealId);
}

export function getMediaStats(dealId: string) {
  const items = getMediaByDeal(dealId);
  const byCategory: Partial<Record<string, number>> = {};
  for (const item of items) {
    byCategory[item.category] = (byCategory[item.category] ?? 0) + 1;
  }

  const required = ["exterior", "kitchen", "living_room", "bedroom", "bathroom"];
  const missing = required.filter((r) => !byCategory[r]);
  const completeness = Math.round(((required.length - missing.length) / required.length) * 100);

  return {
    total: items.length,
    by_category: byCategory,
    completeness_score: completeness,
    missing_rooms: missing.map((r) => r.replace(/_/g, " ")),
    cover_photo: items.find((i) => i.is_cover),
  };
}
